name = "chishenmo"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "FOOD_KV"
id = "a2eeadc68c8f4ca2b6b58a48f7dd5ec3"
preview_id = "c540a8f9668f40958af7fa27275562df"